name: repo_search_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  flutter_bloc: ^9.1.0
  http: ^0.13.6
  bloc: ^9.0.0
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.4.1
  build_runner: ^2.3.3
  json_serializable: ^6.7.1

flutter:


  uses-material-design: true

  assets:
    - .env

